// Protocol for loading and inspecting TLS certificates.
// Used to read the PEM files generated by Tailscale and to check
// whether they are still valid or need renewal.
import Foundation

protocol CertificateProviding: Sendable {

    /// Reads a TLS certificate and its private key from PEM files on disk.
    ///
    /// - Parameter certPath: Absolute path to the PEM-encoded certificate file.
    /// - Parameter keyPath: Absolute path to the PEM-encoded private key file.
    /// - Returns: A tuple containing the certificate PEM string (`cert`) and the
    ///   private key PEM string (`key`).
    /// - Throws: If either file does not exist, is not readable, or is not valid PEM.
    func loadCertificate(certPath: String, keyPath: String) throws -> (cert: String, key: String)

    /// Parses the certificate at the given path and returns its expiration date.
    ///
    /// - Parameter certPath: Absolute path to the PEM-encoded certificate file.
    /// - Returns: The `Date` when the certificate expires (the "Not After" field).
    /// - Throws: If the file cannot be read or the certificate cannot be parsed.
    func certificateExpiryDate(certPath: String) throws -> Date

    /// Checks whether the certificate at the given path is close to expiring
    /// or has already expired, indicating that it should be renewed.
    ///
    /// - Parameter certPath: Absolute path to the PEM-encoded certificate file.
    /// - Returns: `true` if the certificate expires within a renewal window
    ///   (e.g. 7 days) or has already expired; `false` if it is still valid.
    /// - Throws: If the file cannot be read or the certificate cannot be parsed.
    func needsRenewal(certPath: String) throws -> Bool
}
